### PR TITLE
uncompressed dependencies

### PR DESCRIPTION
**Pull request by klausbayrhammer**
#49 Add option to store dependencies compressed
Recreated pull request 50. Although everything should merge cleanly into master.

### CODE REVIEW

**Comment by marius-c** [comment]
Any update when this will be merged ?

**Comment by hollandben** [comment]
Would be great to get an update on this @swarajban - anything we can do to help this get merged?

**Comment by swarajban** [comment]
Looks like this PR hasn't merged in the latest `feature/pull-requests`. The `jspm` support is missing in the the current PR. Can you please re-merge and update here?

**Comment by swarajban** [comment]
Closing this until it is brought back up to date

**Comment by lunetics** [comment]
any updates?

**Comment by swarajban** [comment]
Did you have a chance to merge in latest changes from master?

**Pull request closed without merging**
