### PR TITLE
Move from node-tar to tar-fs. 

### LINKED ISSUE #53: tar-fs vs node-tar
I read another issue about performance. Ran across this test: 
https://gist.github.com/mafintosh/8102201

Is it possible to use tar-fs instead of node-tar if this test is really correct, and I'm not misunderstanding anything.

### PR DESCRIPTION
**Pull request by STRML**
About 2x performance over node-tar.

Fixes #53.

Should make #49 redundant. I haven't seen any performance boost in not compressing. In fact, on most machines the reduced I/O from compression & tar should greatly outweigh the CPU it costs, especially on slow storage subsystems like EBS.

### CODE REVIEW

**Comment by STRML** [comment]
On a project with very large node_modules (226MB), i7 rMBP, installing from cache:

#### Extraction:

`master`: `68.23 real        57.23 user        11.41 sys`
This branch (compression on): `15.23 real         9.24 user         8.84 sys`
This branch (compression off): `15.89 real         8.71 user         8.76 sys

### Archival:

`master`: `32.60 real        26.80 user         6.16 sys`
This branch (compression on): `26.10 real        25.49 user         4.90 sys`
This branch (compression off): `21.29 real        18.41 user         4.58 sys`

For comparison, a raw `cp` of the same folder: `9.21 real         0.44 user         7.74 sys`

One caveat - appears the two formats are very slightly different from each other - I've seen extraction errors with existing archives.

Given the negligible gains from turning compression off, I don't see any pressing need to provide an option.

**Comment by STRML** [comment]
I'm seeing the `npm install` step of our build go from 58s to 17s with this branch. 👍

**Comment by swarajban** [comment]
This PR had conflicts after adding ability to not compress deps. Just incorporated in latest release though. Thanks!

**Comment by STRML** [comment]
Great! Thanks.

**Pull request closed without merging**
